if __name__ == '__main__':
    print('Task 13. Coordinate.')
    x = input()
    print(x, id(x))
    x = int(x)
    print(x, id(x))
    y = input()
    y = int(y)
    print(y)
    z = input()
    z = int(z)
    print(z)
    coordinate = (x, y, z)
    print('Coordinate',  coordinate)
